export const NAVIGATION_AUTH_LOADING_STACK: string =
  'NAVIGATION_AUTH_LOADING_STACK';
export const NAVIGATION_AUTH_LOADING_SCREEN: string =
  'NAVIGATION_AUTH_LOADING_SCREEN';
export const NAVIGATION_AUTH_STACK: string = 'NAVIGATION_AUTH_STACK';
export const WELCOME_SCREEN: string = 'WELCOME_SCREEN';
export const MORE_SCREEN: string = 'MORE_SCREEN';

export const BACKGROUND_STATE_SCREEN: string = 'BACKGROUND_STATE_SCREEN';
export const QUIT_STATE_SCREEN: string = 'QUIT_STATE_SCREEN';
export const FOREGROUND_STATE_SCREEN: string = 'FOREGROUND_STATE_SCREEN';
